import './globals.css'
import localFont from 'next/font/local'
import { Crimson_Pro, Inter } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const pally = localFont({
  src: '../../public/fonts/pally/Pally-Variable.ttf',
  variable: '--font-pally',
})
const crimson = Crimson_Pro({
  variable: '--font-crimson',
  subsets: ['latin'],
})
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${pally.variable} ${crimson.variable} ${inter.variable}`}
    >
      <body>{children}</body>
    </html>
  )
}
